import bcrypt from "bcryptjs";
import { tenantData } from "./seed-source";

const TENANTS = [
  // 一旦は全テナント月額（billing_rule）。
  { id: "00000000-0000-0000-0000-000000000001", name: "Union", slug: "union", billing_rule: '{"type":"monthly"}' },
  { id: "00000000-0000-0000-0000-000000000002", name: "三信産業", slug: "sanshin", billing_rule: '{"type":"monthly"}' },
];

const ADMIN_USERS: { tenant_slug: string; email: string }[] = [
  { tenant_slug: "union", email: "admin@kensetsu-tech.com" },
];

const TEST_CUSTOMER_PASSWORD = "demo1234";
const TEST_CUSTOMERS: {
  tenant_slug: string;
  company_id: string;
  name: string;
  phone: string | null;
  default_address: string | null;
  contact_email: string | null;
}[] = [
  {
    tenant_slug: "sanshin",
    company_id: "C-DEMO-001",
    name: "デモ建設株式会社",
    phone: "097-000-0001",
    default_address: "大分県大分市新貝6番7号",
    contact_email: "demo@example.com",
  },
];

function sqlString(s: string | null | undefined): string {
  if (s === null || s === undefined) return "null";
  return "'" + s.replace(/'/g, "''") + "'";
}

function sqlJsonb(obj: Record<string, string> | null | undefined): string {
  if (!obj || Object.keys(obj).length === 0) return "'{}'::jsonb";
  return sqlString(JSON.stringify(obj)) + "::jsonb";
}

function sqlInt(n: number | null | undefined): string {
  return n === null || n === undefined ? "null" : String(n);
}

const lines: string[] = [];

lines.push("-- ============================================================");
lines.push("-- Demo seed data (auto-generated by scripts/generate-seed.ts)");
lines.push("-- Loaded by `supabase db reset` for local/demo environments only.");
lines.push("-- NOT applied to production via `supabase db push`.");
lines.push("-- ============================================================");
lines.push("");

lines.push("-- tenants");
const tenantValues = TENANTS.map(
  (t) =>
    `  ('${t.id}', ${sqlString(t.name)}, ${sqlString(t.slug)}, ${sqlString(t.billing_rule)}::jsonb)`
).join(",\n");
lines.push(
  `insert into tenants (id, name, slug, billing_rule) values\n${tenantValues};`
);
lines.push("");

lines.push("-- admin_users (allowlist for /admin sign-in)");
const adminValues = ADMIN_USERS.map((a) => {
  const tenant = TENANTS.find((t) => t.slug === a.tenant_slug);
  if (!tenant) throw new Error(`unknown tenant slug for admin: ${a.tenant_slug}`);
  return `  ('${tenant.id}', ${sqlString(a.email)})`;
}).join(",\n");
lines.push(`insert into admin_users (tenant_id, email) values\n${adminValues};`);
lines.push("");

lines.push("-- customers (テスト借り主アカウント。パスワードは全員 'demo1234')");
const customerValues = TEST_CUSTOMERS.map((c) => {
  const tenant = TENANTS.find((t) => t.slug === c.tenant_slug);
  if (!tenant) throw new Error(`unknown tenant slug for customer: ${c.tenant_slug}`);
  const hash = bcrypt.hashSync(TEST_CUSTOMER_PASSWORD, 10);
  return `  ('${tenant.id}', ${sqlString(c.company_id)}, ${sqlString(c.name)}, ${sqlString(hash)}, ${sqlString(c.phone)}, ${sqlString(c.default_address)}, ${sqlString(c.contact_email)}, false)`;
}).join(",\n");
lines.push(
  `insert into customers (tenant_id, company_id, name, password_hash, phone, default_address, contact_email, must_change_password) values\n${customerValues};`
);
lines.push("");

for (const tenant of TENANTS) {
  const data = tenantData[tenant.slug];
  if (!data) {
    throw new Error(`tenantData not defined for slug: ${tenant.slug}`);
  }
  const { categories, materials, offices } = data;

  lines.push(`-- ==================== tenant: ${tenant.slug} ====================`);
  lines.push("");

  lines.push(`-- offices (${tenant.slug})`);
  if (offices.length === 0) {
    lines.push("-- (none)");
  } else {
    const officeValues = offices
      .map(
        (o) =>
          `  ('${tenant.id}', ${sqlString(o.name)}, ${sqlString(o.area)}, ${sqlString(o.address)}, ${sqlString(o.phone)}, ${sqlString(o.fax)}, ${o.sort_order}, ${o.is_active})`
      )
      .join(",\n");
    lines.push(
      `insert into offices (tenant_id, name, area, address, phone, fax, sort_order, is_active) values\n${officeValues};`
    );
  }
  lines.push("");

  lines.push(`-- categories (${tenant.slug})`);
  const categoryValues = categories
    .map(
      (c) =>
        `  ('${tenant.id}', ${sqlString(c.name)}, ${sqlString(c.slug)}, ${sqlString(c.image_url)}, ${c.sort_order})`
    )
    .join(",\n");
  lines.push(
    `insert into categories (tenant_id, name, slug, image_url, sort_order) values\n${categoryValues};`
  );
  lines.push("");

  lines.push(`-- materials (${tenant.slug})`);
  const materialValues = materials
    .map((m) => {
      const catSlug = categories.find((c) => c.id === m.category_id)?.slug;
      return `  ('${tenant.id}', (select id from categories where tenant_id='${tenant.id}' and slug=${sqlString(catSlug!)}), ${sqlString(m.name)}, ${sqlString(m.description)}, ${sqlJsonb(m.spec)}, ${sqlInt(m.daily_price)}, ${sqlInt(m.monthly_price)}, ${m.sort_order}, ${m.is_active})`;
    })
    .join(",\n");
  lines.push(
    `insert into materials (tenant_id, category_id, name, description, spec, daily_price, monthly_price, sort_order, is_active) values\n${materialValues};`
  );
  lines.push("");

  const urlSet = new Set<string>();
  for (const m of materials) {
    if (m.image_url) urlSet.add(m.image_url);
    for (const p of m.catalog_pages || []) urlSet.add(p);
  }
  const urls = Array.from(urlSet).sort();

  if (urls.length === 0) {
    lines.push(`-- images / material_images (${tenant.slug}): 画像なし`);
    lines.push("");
    continue;
  }

  lines.push(`-- images (${tenant.slug})`);
  const imageValues = urls
    .map((u) => `  ('${tenant.id}', ${sqlString(u)})`)
    .join(",\n");
  lines.push(`insert into images (tenant_id, url) values\n${imageValues};`);
  lines.push("");

  lines.push(`-- material_images (${tenant.slug})`);
  type MILink = {
    name: string;
    category_slug: string;
    url: string;
    sort_order: number;
    is_primary: boolean;
  };
  const miLinks: MILink[] = [];
  for (const m of materials) {
    const catSlug = categories.find((c) => c.id === m.category_id)?.slug;
    if (!catSlug) continue;
    const seen = new Set<string>();
    let order = 0;
    if (m.image_url) {
      miLinks.push({
        name: m.name,
        category_slug: catSlug,
        url: m.image_url,
        sort_order: order++,
        is_primary: true,
      });
      seen.add(m.image_url);
    }
    for (const p of m.catalog_pages || []) {
      if (seen.has(p)) continue;
      miLinks.push({
        name: m.name,
        category_slug: catSlug,
        url: p,
        sort_order: order++,
        is_primary: false,
      });
      seen.add(p);
    }
  }
  const miValues = miLinks
    .map(
      (l) =>
        `  (${sqlString(l.name)}, ${sqlString(l.category_slug)}, ${sqlString(l.url)}, ${l.sort_order}, ${l.is_primary})`
    )
    .join(",\n");
  lines.push(`insert into material_images (material_id, image_id, sort_order, is_primary)
select m.id, i.id, v.sort_order, v.is_primary
from (values
${miValues}
) as v(material_name, category_slug, image_url, sort_order, is_primary)
join categories c on c.tenant_id='${tenant.id}' and c.slug = v.category_slug
join materials m on m.tenant_id='${tenant.id}' and m.category_id = c.id and m.name = v.material_name
join images i on i.tenant_id='${tenant.id}' and i.url = v.image_url;`);
  lines.push("");
}

console.log(lines.join("\n"));
